### ISSUE TITLE
it could work as a chrome extension ?

### ISSUE THREAD

**Issue by madruga8** [HalilCan/headless-chatgpt#1]
Hello, congratulations on the idea. I'm curious if it could function as a Chrome extension that serves as an API for web apps, even those that aren't necessarily Chrome extensions.

**Comment by HalilCan** [comment]
Thanks. 
On your question: Yes, I think so. [Native Messaging (Mozilla)](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging) and [Native Messaging (Chrome)](https://developer.chrome.com/docs/extensions/mv3/nativeMessaging/) would probably be the way to go there. Why do you ask?

**Comment by HalilCan** [comment]
I assume this is concluded. If not, feel free to reach out.
